spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mi_basedatos
    username: postgres
    password: mi_contraseña
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html